name: wifi_direct_cable
description: "Everything you can do with wifi direct."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  win32: ^5.0.0
  win32_registry: ^1.0.0
  path: ^1.8.0
  provider: ^6.1.1
  geolocator: ^14.0.2
  ffi: ^2.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.7

plugin:
  platforms:
    android:
      package: com.example.wifi_direct_cable
      pluginClass: WifiDirectCablePlugin


msix_config:
  display_name: WDCable
  sign_msix: false
  publisher: "CN=WDCableCorp, OID.2.25.311729368913984317654407730594956997722=1"
  publisher_display_name: WDCableCorp
  identity_name: WDCable.Desktop
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  capabilities: "internetClient, privateNetworkClientServer location"
  device_capabilities: "wiFiControl, proximity, radios"
  #store: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

